- docs/HISTORY.txt
- setup.py
The new ``COMPONENT_REGISTRY_ISOLATION`` testing layer introduced a dependency to p.a.testing, which was not properly declared.
> Declare missing dependency to p.a.testing

- ftw/testing/tests/test_testcase.py
- setup.py
The TestToolMocking test suite depends on having Products.PloneHotfix20121106,
which is bad because those hotfixes are incorporated in the newest Plone hotfix releases.
This causes the test to break on Plone 4.2 because the hotfix does no longer apply.
This removes the regression test which tests that getToolByName is mocked and released
properly even when it is patched before by a hotfix.
We cannot test this properly for all supported Plone versions because the hotfix does
not apply.
It is also not a good idea to have a dependency on a hotfix when test the latest
hotfix versions, since the required hotfixes change.
> Remove dependency to Products.PloneHotfix20121106 and tests.

- README.rst
- ftw/testing/__init__.py
- ftw/testing/staticuids.py
- ftw/testing/tests/test_staticuids.py
The static uid decorator allows to replace the uid generator utility temporaryily with a static uid generator, so that we can easily assert uids in tests.
Example:
```python
from ftw.testing import staticuid
from plone.app.testing import PLONE_INTEGRATION_TESTING
from unittest2 import TestCase
class MyTest(TestCase):
layer = PLONE_INTEGRATION_TESTING
@staticuid()
def test_all_the_things(self):
doc = self.portal.get(self.portal.invokeFactory('Document', 'the-document'))
self.assertEquals('testallthethings0000000000000001', IUUID(doc))
@staticuid('MyUIDS')
def test_a_prefix_can_be_set(self):
doc = self.portal.get(self.portal.invokeFactory('Document', 'the-document'))
self.assertEquals('MyUIDS00000000000000000000000001', IUUID(doc))
```
@maethu
> Implement staticuids decorator.

- README.rst
- docs/HISTORY.txt
- ftw/testing/freezer.py
- ftw/testing/tests/test_freezer.py
The ``forward`` and ``backward`` methods allows to easily update the freezed time.
```python
from ftw.testing import freeze
from datetime import datetime
with freeze(datetime(2014, 5, 7, 12, 30)) as clock:
clock.forward(days=2)
clock.backward(minutes=15)
```
> Update the freezed time with "forward" and "backward".

- docs/HISTORY.txt
- ftw/testing/freezer.py
- ftw/testing/tests/test_freezer.py
- setup.py
With this change the freezed datetime handler, accept  and handles now the `tz` parameter correctly.
I've implemented the support as follows:
- `datetime.now()` return always an timezone unaware datetime
- `datetime.now(timezone)` return the freezed datetime in the given timezone.
@jone @lukasgraf
> Added timezone suppor for "freeze" helper.

- docs/HISTORY.txt
- ftw/testing/freezer.py
- ftw/testing/tests/test_freezer.py
**Problem:**
When committing objects with freezed dates, there were pickling errors, such as:
```python
Traceback (most recent call last):
File "/Users/jone/projects/python/cache/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340, in run
testMethod()
File "/Users/jone/projects/packages/ftw.testing/ftw/testing/tests/test_freezer.py", line 162, in test_commit_works_with_transactions
transaction.commit()
File "/Users/jone/projects/python/cache/eggs/transaction-1.1.1-py2.7.egg/transaction/_manager.py", line 89, in commit
return self.get().commit()
File "/Users/jone/projects/python/cache/eggs/transaction-1.1.1-py2.7.egg/transaction/_transaction.py", line 329, in commit
self._commitResources()
File "/Users/jone/projects/python/cache/eggs/transaction-1.1.1-py2.7.egg/transaction/_transact …
```
> Freezer: add commit support

- README.rst
- docs/HISTORY.txt
- ftw/testing/__init__.py
- ftw/testing/exceptions.py
- ftw/testing/tests/test_transaction_interceptor.py
- ftw/testing/transaction_interceptor.py
The ``TransactionInterceptor`` patches Zope's transaction manager in order to prevent code from interacting with the transaction.
This can be used for example for making sure that no tests commit transactions when they are running on an integration testing layer.
The interceptor needs to be installed manually with ``.install()`` and removed at the end with ``.uninstall``. It is the users responsibility to ensure proper uninstallation.
When the interceptor is installed, it is not yet active and passes through all calls. The intercepting begins when ``.intercept()`` and ends when ``.clear()`` is called.
```python
from ftw.testing import TransactionInterceptor
interceptor = TransactionInterceptor().install()
try:
interceptor.intercept(interceptor.BEGIN | interceptor.COMMIT | …
```
> Add transaction interceptor.

- docs/HISTORY.txt
- ftw/testing/__init__.py
- setup.py
The Plone package is a wrapper package which is not installed by default in Plone tests. We should rely on "Products.CMFPlone", not on "Plone".
> Do not require "Plone" egg.

- docs/HISTORY.txt
- ftw/testing/tests/test_transaction_interceptor.py
- ftw/testing/transaction_interceptor.py
Extend the transaction interceptor with a savepoint simulation mode. The savepoint simulation mode simulates a transaction by using a savepoint in order to be able to roll back.
This will help in situations where transaction commits cannot be avoided but should not be executed.
> Add savepoint simulation to transaction interceptor.

- docs/HISTORY.txt
- ftw/testing/tests/test_transaction_interceptor.py
- ftw/testing/transaction_interceptor.py
The savepoint simulation clenaup so that it removes the savepoint. This is important when the interceptor is resued later when the prior savepoint is no longer valid.
> Fix savepoint simulation to cleanup savepoints.

- docs/HISTORY.txt
- ftw/testing/freezer.py
- ftw/testing/tests/test_freezer.py
The time.time() function was off by one hour when no tzinfo was provided while freezing a summer time. All functions basing on time.time(), such as datetime.today(), were off too.
We now use mktime() for building the time instead of calculating it ourselve. mktime() can handle the case where tm_isdst is -1 (=undecided).
Closes #19
> Freezer: Fix DST-bug in today() and time().

- docs/HISTORY.txt
- ftw/testing/freezer.py
- ftw/testing/tests/test_freezer.py
When freezing a specific datetime with a tzinfo, the tzinfo should be keept when moving the clock forward and backward.
The timezone info was lost when using `.forward()` and `.backward()` because it used `datetime.now()` as basis, which returns a timezone naïve object. By using the actually freezed datetime object we always have the same timezone (or none) after moving the clock.
> Freezer: keep timezone info when moving clock forward / backward.

- docs/HISTORY.txt
- ftw/testing/layer.py
With Plone 5.1, the testing-buildout used by the ConsoleScriptLayer requires to already have a zope.untrustedpython available.
> Support Plone 5.1 for ConsoleScriptLayer.

- README.rst
- docs/HISTORY.txt
- ftw/testing/__init__.py
- ftw/testing/integration_testing.py
- ftw/testing/testing.py
- ftw/testing/tests/test_integration_testing.py
- setup.py
The new integration testing layer and its test case help setting up a testing environment with database isolation and transaction handling.
It makes it possible to use ftw.testbrowser's traversal driver with integration testing.
The test case provides helper methods. It can be extended with more useful helpers and assertion methods for testing Plone addons.
The code is mostly copied from `opengever.core`.
> Add FTWIntegrationTesting and FTWIntegrationTestCase.

- docs/HISTORY.txt
- ftw/testing/freezer.py
- ftw/testing/tests/test_freezer.py
I could not quickly figure out how to unnaive the `utcnow()` freezing.
> Also freeze datetime.utcnow()

- docs/HISTORY.txt
- ftw/testing/staticuids.py
- ftw/testing/tests/test_staticuids.py
It should be possible to use staticuid multiple times within the same function with different prefixes.
staticuid did only support beeing used as function decorator, therefore this use case was only possible by using nested functions, which is not very readable.
With this change staticuid can also be used a context manager, while it can still be used as decorator.
> Extend "staticuid" to also be a context manager.

- docs/HISTORY.txt
- ftw/testing/freezer.py
- ftw/testing/tests/test_freezer.py
When freezing with a timezone unaware datetime, getting now for a given timezone would fail. Instead we now assume the same timezome for the freezing time as passed in the "now" method call.
This problem arises in GEVER, when freezing with a timezone unaware `datetime` and then updating a document title, which fires an SQL query with a timezone aware now as `modified` date.
The chosen solution also seems to match with what is done in `freezegun` (https://github.com/spulec/freezegun/)
> Fix bug with getting a timezone aware "now".

- docs/HISTORY.txt
- ftw/testing/freezer.py
- ftw/testing/tests/test_freezer.py
The freezer freezes the python datetime as well as the system time. The problem is that when freezing the system time, all information about the timezone is lost. Zope DateTime then uses the system time and the local timezone to construct its current time. We fix this by adding the offset to the local timezone to the timetuple when freezing the system time.
> Fix timezone issue in freezer for Zope DateTime.

- docs/HISTORY.txt
- ftw/testing/freezer.py
The new stack-inspection-on-read logic of time freezing has proven expensive and has roughly tripled the fixture build time of `opengever.core` from just over one minute to about three and a half minutes. It also seems to have added about a minute to the runtime of the test server self test run.
I've side stepped this by only inspecting the stack if the user has explicitly passed in an iterable of module names to ignore.
Build of current master  of `opengever.core` ~19 minutes:
https://ci.4teamwork.ch/builds/233225
Build of current master of `opengever.core` against this branch ~16 minutes:
https://ci.4teamwork.ch/builds/233238
Two main culprits for this being so heavy:
1) `inspect.stack()` iterates over the `.items()` of potentially very large dictionaries
2) `inspect.getmodule()` hits …
> Optimize ignore_modules to avoid unneeded stack inspections

- README.rst
- docs/HISTORY.txt
Reverts 4teamwork/ftw.testing#42
unittest2 is only needed for python < 2.7.
> Revert "Update Readme."

- docs/HISTORY.txt
- ftw/testing/testcase.py
Do not tear down the component registry in `MockTestCase` as it's
handled by the `ComponentRegistryLayer`.
> Fix component registry tear down in MockTestCase

- docs/HISTORY.txt
- ftw/testing/genericsetup.py
This could unhide some test failures, but unlikely
> Fixes for uninstall tests: restore diffs, and run in Plone 5.1

- docs/HISTORY.txt
- ftw/testing/freezer.py
This fixes the severe performance problem with opengever.core testserver.
> Significantly optimize freezer's "ignore_modules"

- ftw/testing/__init__.py
- ftw/testing/genericsetup.py
- ftw/testing/tests/test_mailing.py
Fixes the currently failing tests for `ftw.testing`:
- Fix genericsetup uninstall profile test:
For `Plone >= 5.2` a registry record `custom_css_timestamp` for `plone.app.theming.interfaces.IThemeSettings` exists that screwed up the GS profile snapshot diffing.
That record has both a datetime `value` and a `defaultFactory` with `datetime.now()` that need to be neutralized in order for the diff not to change all the time.  
- Fix mailing tests:
The email messages captured by the `MockMailHost` are represented as bytestrings.
This is not wrong, since sending mails via Zope's MailHost is very close to SMTP, and over SMTP one transmits *bytes*, not necessarily *text*. SMTP will only ever send 7-bit ASCII over the network, any encoding of non-ASCII characters happens inside the RFC 822 …
> Fix mailing and genericsetup tests

- docs/HISTORY.txt
- ftw/testing/freezer.py
In some cases (template expressions) the module of the current frame can't be get and with the current implementation an `AttributeError: 'NoneType' object has no attribute '__name__'` occurs.
By just handling those callers as not ignored, we can fix this problem.
Problems occurs in opengever.core testserver-selftests when bumping to latest ftw.testing version (see [CA-1240](https://4teamwork.atlassian.net/browse/CA-1240))
> Make freezer's "ignore_modules" more robust.
